### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by devinaflynn** [LeviBotelho/LearnAngular#29]
I feel like the lessons are really good, but the only I would say is that I would like it more it the lessons were broken down into smaller lessons. Also, I would like it if you told the user where to place the code during the lessons. For example, It never says "place the code below in the html tag on the index.html page", so I feel the user, especially beginners, will have trouble knowing what to do. Angular is pretty sweet though. Thanks :)

**Comment by LeviBotelho** [comment]
Hi, fair point about the lessons. If there are specific areas that you feel could be improved feel free to fork. I'm happy to consider any pull requests that improve the overall quality of the service :).
