### ISSUE TITLE
"Two-way bindings" not working?

### ISSUE THREAD

**Issue by arangas** [LeviBotelho/LearnAngular#30]
Unless I'm missing something, the [Two-way bindings](http://learn-angular.org/#!/lessons/two-way-bindings) "Run" code doesn't seem to be doing anything. The page doesn't really describe what it should do but I'm guessing when a control loses focus it should update the "[Display selection here]" text?

**Comment by LeviBotelho** [comment]
> Once the values are bound, use the double curly brace syntax to display each value next to its corresponding input and run the example to see two-way binding in action!

?

**Comment by arangas** [comment]
Apologies for wasting your time, I didn't complete the lesson *facepalm*

**Comment by LeviBotelho** [comment]
No worries mate ;).
