### ISSUE TITLE
Resource URL is too picky

### ISSUE THREAD

**Issue by marnen** [LeviBotelho/LearnAngular#32]
Thanks for the tutorial! I spent a few sheepish minutes wondering why my code for the resource lesson wasn't working, until I realized that the browser was pointed to `learn-angular.org`, while the resource URL given in the lesson was from `www.learn-angular.org`, so I got the following error in the JavaScript console:

`XMLHttpRequest cannot load http://learn-angular.org/ResourceLesson/Users/1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.learn-angular.org' is therefore not allowed access.`

Perhaps it's worth declaring that header?

**Comment by LeviBotelho** [comment]
Alright I've added allow * to the web.config file, so this is fixed. Doesn't pose any security issues because there's no site login :).

**Comment by marnen** [comment]
Thank you!
