### ISSUE TITLE
Error while saving data in an exercise

### ISSUE THREAD

**Issue by sandeshjkota** [LeviBotelho/LearnAngular#35]
I get an error when i try to save the User in the below exercise
http://learn-angular.org/#!/lessons/ajax-with-resource

Error message: "XMLHttpRequest cannot load http://www.learn-angular.org/ResourceLesson/Users. Request header field Content-Type is not allowed by Access-Control-Allow-Headers"

**Comment by misfist** [comment]
I get this same error when trying to save the user:

http://learn-angular.org/#!/lessons/ajax-with-resource

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.learn-angular.org/ResourceLesson/Users. (Reason: missing token 'content-type' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.learn-angular.org/ResourceLesson/Users. (Reason: CORS request failed).

**Comment by LeviBotelho** [comment]
Going to force all visitors to www with a DNS record. That should fix it. I'll let you folks know when it appears to have propagated so you can give it a shot.

**Comment by LeviBotelho** [comment]
The DNS modification has propagated. You shouldn't get this error anymore as all requests should be same origin, coming from www.learn-angular.org.
