### ISSUE TITLE
Chrome: blocked a frame from origin "http://learn-angular.org" from accessing a cross-origin frame

### ISSUE THREAD

**Issue by aggieben** [LeviBotelho/LearnAngular#36]
![image](https://cloud.githubusercontent.com/assets/1321/7847869/3c9b7fa4-048c-11e5-9f6c-d3b96739c393.png)

**Comment by LeviBotelho** [comment]
What was the url that you were accessing at the time? I recently had to change some DNS settings on the site and IIRC all traffic from http://www.learn went to http://learn, which doesn't appear to be the case anymore. Can you please confirm that this works at the http://learn url and not at the http://www.learn url for me?

**Comment by aggieben** [comment]
I went here: http://learn-angular.org/#!/lessons/the-essentials

I don't know why I didn't do this before, I tried this using incognito mode in Chrome, and it worked.  I narrowed it down to: Readability 3.0.15 (I have _no_ idea why).

**Comment by LeviBotelho** [comment]
Wow very weird. I honestly don't intend on fixing this because I think it'll take far more time than it's worth, but if you or anyone else reading this would like to give it a shot I'm more than happy to accept pull requests :smile:.
