### ISSUE TITLE
... learn which version of angular?

### ISSUE THREAD

**Issue by franciscotrillo** [levibotelho/LearnAngular#47]
This may be me being stupid but the site doesn't seem to specify which angular it's teaching you, 1.x or 2.0. And someone who has never seen angular before, like me, might not be able to just tell by looking at the code.

**Comment by levibotelho** [comment]
Yup, good point. I wrote this well before Angular 2 came out but it's definitely worth mentioning.

**Comment by levibotelho** [comment]
Fixed in master. I'll deploy this next week.
