### ISSUE TITLE
Nice explanation. One more point. 

### ISSUE THREAD

**Issue by samraosmanova** [levibotelho/LearnAngular#53]
Nice explanation. Thank you. 

One more point.  Can't make code work until one doesn't write with exact indention as your code. Even if i write code with proper logic and syntax, it doesn't accept.

**Comment by levibotelho** [comment]
This can't be right. All the site does is parse whatever is in the text field as JavaScript and runs it, there is no reformatting and no checking of any kind done to what you type. Can you provide an example?

**Comment by samraosmanova** [comment]
previously in Factory Recipe I wrote the code by my own and it didn't execute. I clicked "I got stuck". And everything seemed the same as my code.  Now I have written one more time to provide example for you and everything works just  fine, and looks like it was my syntax mistake somewhere. 

Sorry for inconvenience.

**Comment by levibotelho** [comment]
No problem!
