### ISSUE TITLE
Constant recope

### ISSUE THREAD

**Issue by devpaaji** [levibotelho/LearnAngular#55]
when I run the program in constant recipe sample, the template displays {{message}}

the message.constant value does not appear. check the run tab

**Comment by devpaaji** [comment]
In this exercise
how is main controller coming to know about the config - constant value and displaying in the html
 ```
// now let us first configure our provider
        myModule.config(["messageProvider", "messageText", function (messageProvider, messageText) {
            messageProvider.setText(messageText);

        }]);

        myModule.controller("constantController", ["$scope", "message", function ($scope, message) {
            $scope.message = message.text;
        }]);
```

`<div ng-controller="constantController">{{message}}</div>`

**Comment by levibotelho** [comment]
Hi, this issue tracker is for bugs in LearnAngular and not for Angular questions. If you have questions regarding your code, I would recommend you post them on StackOverflow or a similar site.

**Comment by devpaaji** [comment]
Noted.

Can you still give me a brief about my question. It was an important
concept for learning.
