### ISSUE TITLE
First lesson bug

### ISSUE THREAD

**Issue by ionoproxy** [levibotelho/LearnAngular#56]
Hello there, I recently found a bug in your website and I just wanna get you to know it in order to fix it.

If you access the link via Google you get this address: http://www.learn-angular.org/?_escaped_fragment_=#!/

Once you start the first lesson, any browser do not display the grid with the following lessons on the left side, and consequently, the guest isn't able to continue with the next lesson once finished the first one, and probably, leaves the page. This bug it's due to the address.

Your welcome,
Greetings.

**Comment by levibotelho** [comment]
Google shouldn't be indexing this URL. I'll look into it, cheers.

**Comment by levibotelho** [comment]
Done what I can. You can remove the escaped_fragment bit and the site will work properly.
