### ISSUE TITLE
Where can we find the .css files?

### ISSUE THREAD

**Issue by johntiger1** [levibotelho/LearnAngular#64]
Specifically for these lessons: (bold, italic, underline and oddrow)
http://www.learn-angular.org/#!/lessons/binding-css-classes
http://www.learn-angular.org/#!/lessons/repeaters

**Comment by levibotelho** [comment]
Behind the scenes = they're referenced in the file but not available for you to play with. You can apply the classes in your code though which is what's done in the solution.
